theme: jekyll-theme-minimal
title: Paula Parpart
logo: /images/Ocropped.jpg
description: Email - paula.parpart@nyu.edu paula.parpart@ucl.ac.uk, Office - 60 5th Ave, Room 643, New York, NY 10011  [Google Scholar](https://scholar.google.co.uk/citations?user=NzxL4G4AAAAJ&hl=en)
