theme: jekyll-theme-minimal
title: Paula Parpart
logo: /images/Ocropped.jpg
description: email - paula.parpart@nyu.edu, 
paula.parpart@ucl.ac.uk
Office address - 60 5th Ave., Room 643, New York, NY 10011


